packages:
  - apps/*
  - packages/*

catalogs:
  bcrypt:
    bcrypt: ^6.0.0
    bcrypt-edge: ^0.1.0
  better-auth1:
    better-auth: ^1.3.4
  bootstrap5:
    bootstrap: ^5.3.7
    react-bootstrap: ^2.10.10
  clsx:
    clsx: ^2.1.1
  cmdk:
    cmdk: ^1.1.1
  date-fns:
    date-fns: ^4.1.0
  daisyui5:
    daisyui: ^5.0.46
  dotenvx:
    '@dotenvx/dotenvx': ^1.48.0
  eslint:
    '@eslint/js': ^9.30.1
    '@eslint/eslintrc': ^3.3.1
    '@next/eslint-plugin-next': ^15.3.5
    '@typescript-eslint/parser': ^8.36.0
    '@typescript-eslint/eslint-plugin': ^8.36.0
    eslint: ^9.30.1
    eslint-config-next: ^15.3.5
    eslint-config-prettier: ^10.1.5
    eslint-plugin-neverthrow: ^1.1.4
    eslint-plugin-only-warn: ^1.1.0
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-turbo: ^2.5.4
    globals: ^16.3.0
    typescript-eslint: ^8.36.0
  jest29:
    '@types/jest': ^29.5.14
    jest: ^29.7.0
    jest-environment-jsdom: ^29.7.0
    ts-jest: ^29.4.0
    ts-node: ^10.9.2
  jest30:
    '@types/jest': ^30.0.0
    jest: ^30.0.4
    jest-environment-jsdom: ^30.0.4
    ts-jest: ^29.4.0
    ts-node: ^10.9.2
  lucide-react:
    lucide-react: 0.525.0
  neverthrow:
    neverthrow: ^8.2.0
  next15:
    next: ^15.4.7
    next-themes: ^0.4.6
  next-auth5:
    '@auth/core': ^0.40.0
    next-auth: ^5.0.0-beta.29
  node20:
    '@types/node': ^20.11.0
    node: 20.19.2
  node22:
    '@types/node': ^22.15.21
    node: ^22.16.0
  node24:
    '@types/node': ^24.0.11
    node: ^24.16.0
  pino:
    pino: ^9.7.0
  postcss:
    postcss: ^8.5.6
  prisma6:
    '@prisma/client': ^6.12.0
    prisma: ^6.12.0
  react19:
    '@types/react': ^19.1.5
    '@types/react-dom': ^19.1.5
    react: ^19.1.0
    react-dom: ^19.1.0
  react-csv:
    react-csv: ^2.2.2
    '@types/react-csv': ^1.1.10
  react-toastify:
    react-toastify: ^11.0.5
  tailwind4:
    tailwind-merge: ^3.3.1
    '@tailwindcss/cli': ^4.1.11
    '@tailwindcss/postcss': ^4.0.0-alpha.13
    tailwindcss: ^4.1.11
    tw-animate-css: ^1.4.0
  tanstack:
    '@tanstack/react-form': ^1.14.1
    '@tanstack/react-table': ^8.21.3
  tsx:
    tsx: ^4.20.3
  typescript5:
    typescript: ^5.8.3
  uidotdev:
    '@uidotdev/usehooks': 2.4.1
  vitest:
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    vitest: ^3.2.4
    vite-tsconfig-paths: ^5.1.4
  zod:
    zod: ^4.0.5

ignoredBuiltDependencies:
  - bcrypt
